export const CLOTHES_LIST = [
    'Sweater',
    'Jacket',
    'Pants',
    'Vest',
    'Coat',
    'Dress',
    'Jeans',
    'Shirt',
    'Shorts',
    'Swimsuit',
    'Skirt',
    'Sock',
    'Pajamas',
    'Cardigan',
    'Suit',
    'Raincoat',
    'Sleeveless shirt',
    'Belt',
    'Other',
  ];