// export const BASE_URL = "http://34.136.31.97:80"
// export const BASE_URL = ""
export const BASE_URL = "http://127.0.0.1:8000"
export const ITEM_LIST_URL = `${BASE_URL}/api/items/`
export const LOGIN_URL = `${BASE_URL}/api/auth/token/`
export const ME_URL = `${BASE_URL}/api/auth/me`
export const SIGNUP_URL = `${BASE_URL}/api/auth/signup/`
export const ADD_ITEM_URL = `${BASE_URL}/api/items/`
export const UPLOAD_PROFILE_IMG_URL = `${BASE_URL}/api/auth/me/img`
export const UPLOAD_ITEM_IMG_URL = `${BASE_URL}/api/items/`
export const GOOGLE_AUTH_URL = `${BASE_URL}/api/auth/google-auth`
export const ITEM_SHERE_URL = `${BASE_URL}/api/item/`